### PR TITLE
inthndlr.c: in Int21.43FF, dispatch DosMkRmdir on CL not AH

### PR DESCRIPTION
**Pull request by andrewbird**
As per discussion in https://github.com/PerditionC/fdkernel/pull/33#issuecomment-552095063 here's ecm's fix

### CODE REVIEW

**Comment by stsp** [comment]
I can in principle just do git pull
on their branch if there is nothing
obviously wrong.

**Comment by andrewbird** [comment]
Will that work? I imagined things would be more complicated to transfer stuff from FreeDOS to FDPP so I did `wget http://github.com/xxxxxx.patch` then `git am xxxxxx.patch`.

**Comment by stsp** [comment]
That should work, trying to repair
my pc and check that out.

**Comment by stsp** [comment]
OK, I have obviously underestimated them. :)
In fact they have a lot (I mean, quite a lot, and not
just from tkchia!) of new stuff and the straight-forward
merging is indeed not possible.

**Comment by stsp** [comment]
> so I did wget http://github.com/xxxxxx.patch then git am xxxxxx.patch.

It is better to set them up as another branch
in your local repo. Then you can just do cherry-picks.

**Comment by stsp** [comment]
fdac78c seems to be the last merge point
(141e6373 is a merge commit in fdpp).
```
$ git diff -r fdac78c fdkernel |diffstat
 50 files changed, 1070 insertions(+), 293 deletions(-)
```
Quite a lot, but its not very accurate because
I have ported the elf patches by hands:
```
$ git diff -r d9cfeb8^^ d9cfeb8 |diffstat
 10 files changed, 140 insertions(+), 112 deletions(-)
```
OK, even if we subtract that - still quite a lot.

**Comment by andrewbird** [comment]
> It is better to set them up as another branch
in your local repo. Then you can just do cherry-picks.

Sounds like a good plan!

**Pull request merged**
