### PR TITLE
api: Add support for kernel symbol handling

### PR DESCRIPTION
**Pull request by andrewbird**
1/ Add the ability to return the kernel map file name

2/ By adding a relocation notification function in the API a
previously loaded set of symbols may be moved as the memory is
relocated.

3/ Install the kernel map file alongside the kernel itself.

### CODE REVIEW

**Comment by stsp** [comment]
The relocations start not at the
beginning of segment. They start
at offset and end at len+offset.

**Comment by andrewbird** [comment]
okay I'll redo.

**Comment by andrewbird** [comment]
So how about `len` i see it's a uint32_t as it's in bytes can it be larger than 0xffff?

**Comment by andrewbird** [comment]
I force pushed the changes, they're trivial here. See the dosemu branch for the maths.

**Comment by stsp** [comment]
Initially I thought about the multi-segment
relocations, where old_seg and new_seg
would only be used to calculate delta, and
len can be large. But in the latest betas
the segments are explicitly compared to
old_seg and replaced with new_seg.
In this scheme it is very unlikely that len
can exceed 0xffff. This solves the problem
with boundary symbols, ie you may have
the end boundary of prev seg and
begin boundary of next seg at the same
address. Distinguishing between them
can only be done by comparing their
segments explicitly, and that leaves no
room for multiseg relocations.

Will look at the patch later.

**Pull request merged**
